//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratorio.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TareaSubtarea
    {
        public int id { get; set; }
        public Nullable<int> idTarea { get; set; }
        public Nullable<int> idSubtarea { get; set; }
    
        public virtual Subtarea Subtarea { get; set; }
        public virtual Tarea Tarea { get; set; }
    }
}
